### ISSUE TITLE
Salt hashed passwords with unique per-user random salt

### ISSUE THREAD

**Issue by bookchin** [storj/bridge#129]

**Comment by bryanchriswhite** [comment]
As we implement this, we'll need to begin storing a user salt and a pending user salt. Taking into consideration the amount of space that these additional values will take up, and the vulnerability we're addressing here I would propose using a salt on the order of 64 bits.

A 64 bit salt provides a 1% probability that any 2 users will have the same (cryptographically) random salt with 610 million users in the database. That probability reaches 25% at 3.3 billion users.

[see the birthday problem probability table](https://en.wikipedia.org/wiki/Birthday_problem#Probability_table)

Given that our objective is to add randomness to the hash input I'd say this sufficiently does the job while not wasting space.

---

Further regarding storage space; @bookchin can you  explain to me how `mongoose.Schema.Types.Mixed` type is works? If this data is being stored as a string I would be curious as to the encoding. I realize this may be dependent on the storage engine but I'm curious as it relates to MMAPv1 as well as WiredTiger.

Currently we're storing hex strings in the fields which use this type. If they are encoded using a character-set which has more than 16 characters we could optomize a bit by matching the encoding.

In the case of MMAPv1 this would save disk space as it does not provide compression like WiredTiger, and in the case of WiredTiger we'd save CPU time.

This may not be that big of a deal at the moment but may at scale and I thought it prudent to consider while we're already here making changes to the `User` model.

**Comment by bryanchriswhite** [comment]
One more quick thing I'd like to understand is our current schema migration strategy if we have one

**Comment by bryanchriswhite** [comment]
for the record - answers from conversation with @bookchin:

- [x] 8 byte (64 bit) user-salts
- [x] try ascii-encoded strings for `resetter`, `activator`, and `deactivator`
  - switch mongoose types to string
- [ ] no current schema migration process - investigate

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
