### ISSUE TITLE
Use Bucket Name for Upload/Download

### ISSUE THREAD

**Issue by super3** [Storj/bridge#186]
### Expected Behavior

Use the bucket name, or create short aliases that you can use.

```
> storj upload-file "Bucket of Cats" cat.jpg
```
### Actual Behavior

Copy and paste the bucket the bucket id you want to use. 

```
> storj list-buckets
 [Fri Aug 19 2016 14:31:09 GMT+0000 (UTC)] [info]   ID: 5772bc64045f13547c8ae62c, Name:                           Bucket of Cats, Storage: 10, Transfer: 30
 [Fri Aug 19 2016 14:31:09 GMT+0000 (UTC)] [info]   ID: 5772bc93045f13547c8ae64c, Name:                           Database Backups, Storage: 10, Transfer: 30
 [Fri Aug 19 2016 14:31:09 GMT+0000 (UTC)] [info]   ID: 579a75e8ee1e331f0357dcf3, Name:                           cdn, Storage: 10, Transfer: 10
 [Fri Aug 19 2016 14:31:09 GMT+0000 (UTC)] [info]   ID: 57b5ff5732a6f29c1fc8b7e9, Name:                           flood2, Storage: 10, Transfer: 10
> storj upload-file 5772bc64045f13547c8ae62c cat.jpg
```

Looks a little rough when trying to demo:

![https://raw.githubusercontent.com/Storj/core/f2c517199510d10028da8b0944abbbf82148e756/doc/assets/demo.gif](https://raw.githubusercontent.com/Storj/core/f2c517199510d10028da8b0944abbbf82148e756/doc/assets/demo.gif)

**Comment by super3** [comment]
There are a few differences of opinions on how this should be implemented. 

1. List-buckets is called inside of the upload-file command to resolve the name to the bucket id
  * In the case of a duplicate, "the first bucket" is chosen for upload
  * In case of a duplicate, the user is prompted to enter a bucket choice
2. Make bucket name unique in bridge
3. Have the client store a copy of the buckets locally, and have a method for the client to know if it is in "sync" with the bridge, so it can properly resolve locally.

**Comment by utdrmac** [comment]
On point 2 above, I would think that means "make bucket name unique, per user". Obviously, you and I can both have buckets named "fave cat pics". If you created that bucket first then I attempted to do so too, I should **not** get some sort of error message saying "that bucket already exists on the network".

**Comment by utdrmac** [comment]
Since you can have more than 1 bucket with the same exact "friendly name", I don't see how you could implement this. How could the CLI know you meant to use "my fav cats" over "my fav cats"? strcmp says those are the same but the bucket hash is different.

**Comment by cpollard1001** [comment]
One approach could be making the bucket id equal to the first 12 bytes of sha256(userEmail + bucketName). That way, the id can automatically be calculated on the client instead of having to run a "list clients" operation.

This approach will automatically prevent a user from creating a second bucket with the same name since it will throw a duplicate ID error.

The downside is that users can't change bucket names or email addresses (since that would evaluate to a new id), and it will only work for newly created buckets.

Also, would it be okay to make the interface to the BridgeClient take either a bucket id or a bucket name? This approach only fails if the name is 24 characters and valid hex, in which case the BridgeClient would assume it is a bucket id. We could make bucket names that fit that characteristic not allowed to prevent that scenario.

**Comment by cpollard1001** [comment]
Updated proposal for deterministic names and ids:

Seed = 12 word mnemonic generated with bitcore-mnemonic
This will be encrypted in file hd_key in folder key.ring

bucketId = HMAC_SHA512(userEmail, bucketName) [userEmail is used as unchanging id for users]
fileId = HMAC_SHA512(bucketId, fileName)
bucketKey = HMAC_SHA512(seed, bucketId)
fileKey = HMAC_SHA512(bucketKey, fileId)

Under this approach, bucket names and file names cannot be changed since they are linked to id. Doing this allows fileId and bucketId lookups without making api calls.

Are there any other issues with making the bucketId/fileId deterministic?
