### ISSUE TITLE
Unable to join network -

### ISSUE THREAD

**Issue by computeronix** [Storj/bridge#193]
### Package Versions

```
C:\Users\storj_bridge_svc\AppData\Roaming\npm
└── storj-bridge@0.11.1
```

```
v4.5.0
```

### Expected Behavior

```
Be able to specify a bridge server or seed to allow the bridge server to connect online
```

### Actual Behavior

```
Every time I start the bridge server the following warning is flagged

{"level":"warn","message":"no bridge or seeds provided, not connected","timestamp":"2016-08-23T12:28:17.045Z"}


Regardless of configuration
```

### Steps to Reproduce

1. Install bridge server
2. Configure it and attempt to add Bridge or Seeds within configuration.  It is not recognized no matter how entered

I have been working with Philip and Gordon on this one - opening this up to document

**Comment by bookchin** [comment]
Ah, this is probably because you have not connected a farmer to your bridge minions. The minions will are started with seeds from the local contacts collection, but if no farmers have ever connected to the bridge, they won't have anyone to connect to.

It also looks like the `bridge` property in the config is not given to the minion constructor, so it's ignored https://github.com/Storj/bridge/blob/master/bin/minion.js#L91
