### ISSUE TITLE
vulnerability: automated scripts - storj register

### ISSUE THREAD

**Issue by littleskunk** [Storj/bridge#203]
Issue reported by @computeronix https://github.com/Storj/core/issues/380

As bridge Operator I would like to have a capture protected user registration. That will exclude bots creating new accounts.

At the moment bots will have no advantage. Later I would like to offer 10GB free storage and payment for more than 10GB. That will attrackt bots creating multiple accounts for more free sotrage.

**Comment by super3** [comment]
@littleskunk Well they still have to activate their accounts via email, so that is one step. I don't think we should put this limitation in place now as it will put up a barrier towards humans and robots. Also this kind of goes against one of my future goals is fully automated usage of Storj. As long as they pay they can create an account. Even if someone created a bunch of accounts it really wouldn't/shouldn't impact us that much.

At this point the more free accounts and the more people on the network the better. Let's think about adding this when we actually have free plans in action. Just too early to add this feature right now.
