### ISSUE TITLE
Payouts script does not exist in bridge any longer

### ISSUE THREAD

**Issue by phutchins** [Storj/bridge#299]
### Package Versions

```
storj-bridge@0.11.4 /opt/storj/bridge-payouts
└── (empty)
```

Replace the values below using the output from `node --version`.

```
v6.9.1
```

### Expected Behavior

```
I would expect for the payouts script to exist and run :).
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
It was removed but never added back.
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Look for the payouts script
2. Realize its not there
3. Get really sad
4. Eat left over pizza

### Some Details
```
I've been hacking it together from the commit before it was removed but it has diverged too far from master for that to be a feasible stop gap. The config for storage is much different now and is causing problems.
```

**Comment by bookchin** [comment]
This was discussed before it was removed in https://github.com/Storj/bridge/releases/tag/v1.0.0-rc.2, since it did not belong here (though even if it were it wouldn't work now anyway). It should be trivial to use https://github.com/Storj/bridge/blob/v0.11.3/script/payouts.js and replace the `../lib/storage` import with the `storj-service-storage-models` package in it's place.

That script should live in another package that is used to calculate debits and credits and integrates with the billing service. @pgerbes is going to be working on this next.
