### ISSUE TITLE
Payout gamble = high risk of losing files

### ISSUE THREAD

**Issue by littleskunk** [Storj/bridge#331]
### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

In order to prevent data loss the bridge creates 5 mirrors. The calculation for this is based on the TGB and TGC results. Most important is the farmer uptime and behavior.

Payout calculation for November was:
* $5 for everyone
* $0,00000175 per GB/h
* $0,000005 per Telemetry report (caped at 17500)
* $0,002 per GB downloaded Bytes

It doesn't realy matter how much we pay as long as it is a stable rule. The $5 for everyone was a littlebit high.
As farmer I would like to be sure that I get more SJCX next month by adding a few more GB free space.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

The current payout calculation for december is a problem. I see more than one high risk losing files. 5 mirrors will not work in this situation.

The current rules (reverse calculated and not acurate):
* $0.58 for each category greater 0. Share 1GB, download 1 Byte and send 1 Telemetry report = $1.74
* Max $10 for the top farmer no matter how good he was.
* Max $5.1 for used space.
* Max $3.5 for telemetry reports.
* Max $1.35 for download bytes.

The payout is not equal. For 10GB the farmer gets $0.00000274. For 1 TB the farmer gets $0.0000000745. 6.7TB $0.0000000157. Same result for telemetry reports and downloads.

Risks:
1.) The payout for 1 TB is so low that many farmer with more than 1TB will drop all shards. All this in a few days. The bridge needs time to recover lost shards. 
Possible solution: It would be better to announce any new rule. Farmer will not rage quit at the same day. They can go offline one by one giving the bridge the time to create new mirrors.

2.) To avoid any penalty the big farmer will split there free space on multiple payout addresses. I used my free time to setup a counterparty-server at home. I am able to create 1000 payout addresses and even more important I can write a script to sell everything with only one call. Not a big deal.
The bridge will get problems to detect that setup. In case of a hardware failure all 1000 nodes will go offline at the same time. A high risk to lose all 5 shards at the same time.
Possible solution: It would be better to pay the first TB the same way you pay the last TB. That was the case on the last payout. Big farmer will setup 1000 nodes but they will use the same payout address for all of them. The bridge can now make sure that all 5 mirrors are placed on different payout addresses. In case of a hardware failure all 1000 nodes will go offline at the same time but the bridge will only use 1 mirror for each shard and can create new mirrors.

3.) Small farmer are sending mails the way you requested it. A few of them get blocked by spam rules. Other user are reporting that they are getting no response even after 2 days. They will delete there shards as well.

Please keep in mind: As long as you give smaller farmer an advantage but still pay a fair price for big farmer, they will follow the rules. They will setup 1000 nodes but point them all to the same payout address. As soon as you pay them the way you do it now they are force to create 1000 nodes with different payout addresses. They can see the consequence but they are force to go this way.

**Comment by littleskunk** [comment]
The focus in this issue is the risk for the renter to lose files. Farmer leaving the game are not a big problem. If they leave all at the same time or are force to play the game in a way that the renter will lose his files is a problem.

**Comment by CJClaude** [comment]
Note that in the USA tax rules favor creation of multiple addresses as well in order to avoid 1099 reporting.  Only the desire to "play by the rules" prevents people from working around it, and via private communication, I understand that at least one of the top 10 users was already using a handful of different addresses to mitigate this.  

As one of the large users (Approx. #28 in October, #4 in November, #1 in December) I'll formally second Littleskunks comments with these additional observations:

1.)  In November, I received something on the order of $3/TB for the space I had allocated.  I have a personal target of $2/TB so was quite happy.  My total payout was just north of $90.  The fact that someone that stored 1GB for that month, 1/37000th of my participation, received 1/18th the payout was accepted because its your money to give away if you wish too.

2.)  In December, I received the maximum payout of approximately $10, or about $0.27/TB for the space I had allocated.  This completely decentivize me from participating at all, since this is well below my long-term expectation of approx. $2/tb/month - not even close.  As such, I immediately shutdown all my nodes, eliminating 37TB of shards from the environment.  A 20X difference in payment between myself and the minimum payed contributor is similar to November's 1/18th (and even closer for the top payee in November), but the absolute value made the difference between participating and not.

3.)  Where up to now, I've tried to participate as a "Good Citizen", the actions of the Storj team have made it clear that doing so tags me as someone to be taken advantage of.  You have set the Storj team up as the "big corporation who is more interested in attracting new customers than keeping old", and as such deserve to be taken advantage of by having farmers play by your rules, on a monthly shifting basis, to maximize their own profits.  Comments about "it will be better next month for large farmers" is meaningless without hard stats.  "Better" could easily be $10.01, which is "better" than $9.98.

4,)  Payment algos should be discussed in advance, and set for a month.  I would suggest that promising minimum payments of any amount will result in people maximizing their profits by focusing on the minimum requirements.  I would propose that to expect anything else is to have more faith in human nature than is warranted.

5,)  I would also suggest than anything that smells of social engineering, and could be viewed as "Taxing the rich to pay for the poor", is counter-free-enterprise, and will not be viewed kindly by those that provide the backbone stable environment Storj is built on.  I predict it will encourage participation by hordes of people that want quick money, have low skills, will require a ton of support, and will likely only bring storage online for a few months before getting bored.  November was fair, if a giveaway to the small participant.  Decembers "flattening" was an insult to your large participants that won't easily be forgiven or forgotten.

Good luck.

**Comment by michaldlouhy** [comment]
So, the first time - I mean - the payout rules would be known before the payout period starts. I understand that it is under develpment, but it will be fair if we had some predicable idea about payouts.
The second, because everyone can make countless nodes with different addresses (as described above) it will be good that the payouts will be same for every GB, regardless how much space the farmer sharing. The sufficient motivation for more peoples participating on the StorJ project is the fixed payout for everyone who is participating on it.
The third, to avoid someone to shut down their node(s) and creating new, will be good some multiplier for the same data that the farmer sharing for the time (of course, if the renter delete his data, it wouldn't penalty the farmet, it would be the same as the farmer sharing the date all the time).

(I farming on 8 PC, runnig 25 nodes with 2950 GB of shared data, 1.92 mio contracts, 1.86 mio GBhours, 11,5 TB downloaded bytes; and also i don't understand why if I have 1.92 mio of contracts, you in payouts proposal calculated only with about 30k contracts; payout address 12Ht97iwzPXqKsrFpj7FxJwNacmcQ69YV8)

**Comment by DontCopyThatFloppy** [comment]
Since this issue was opened to address the Dec 2016 payouts, my response is also directed at the non-retail payouts (i.e. Storj Labs has no shards in the current Storj network that they're being paid US Dollars to maintain access to over time).
From the Risk list in the original post:

**1.** Because the network is only holding test files of no value, or free files (with no promise of reliability, no bridge-audit code running to guarantee availability of those free shards, and that have already been wiped out once with no consequence during the KFS migration)... losing a 1 TB farmer is not a risk, as nothing material would be lost. The risk would actually be keeping those 1TB+/larger farmers happy by paying by capacity: since they're keeping shards online that are of no business value to SL (as SL is not being paid for any space, yet) but they would still see more SJCX compensation. If the lower-bound of utility is about 1GB/m, with a soft cap of around 100GB (eyeballing Dec payout calcs), why should SL pay for the extra 900GB of extra shards a 1TB farmer is holding? They're not helping the project more than a 100GB farmer, but would cost more - that's a business risk SL shouldn't take on.

**2.** From the quote: 

> It would be better to pay the first TB the same way you pay the last TB

See my response to #1 above: that last TB is worth much less that the first - as it's currently useless capacity, not needed, that SL isn't being paid for. When that space is filled with paying renters, _then_ farmers should be paid a linear rate per TB. 

**3.** Regarding small farmers: they've also been in chat complaining about low shard download rates. Yes, the upload volume is small, but they're also competing with the large farmers that are still soaking up many of those files, and have often grown to the size they are because they're running better low-latency setups (they're first-responders for more offers). If SL thinks 1GB->100GB nodes are the sweet spot, then rewards should be dropped until the multi-TB farmers choose to turn off (or reconfigure) their nodes. Looking at #1 again, even if they toss most of their shards when reconfiguring to smaller (but more numerous) node sizes, no important data would be lost.

**In summary**: Until SL starts accepting $$$ to store shards, there's no reason to reward larger farmers based on capacity, because they're not bringing more value to the Storj network: if it's unused space it's just makes payouts more costly.

=======================
_[Edit: in response to CJClaude's 5th comment above]_

From the quote: 

> I would also suggest than anything that smells of social engineering, and could be viewed as "Taxing the rich to pay for the poor", is counter-free-enterprise, and will not be viewed kindly by those that provide the backbone stable environment Storj is built on

I think we're looking at this from different perspectives. If you had 37TB online (behind one payout ID, just for sake or argument) in December, it's not that you were denied a proper payout for 36.9TB (compared to a 100GB farmer who also got $10) - it's that you didn't offer anything more useful to the Storj network than a 100GB farmer, so you were paid the same. (And from when the KFS reset was done: you must agree that to hit 37TB again the majority must have come from before the Dec throttling of uploads: so you're storing TB of garbage test files uploaded by scripts). Nothing was 'taxed' from large farmers: they simply didn't offer anything of value beyond the smaller ones.

But once renters start paying USD, by capacity, and expect to get their files back, all this changes :)

**Comment by bookchin** [comment]
Foregoing a response to @CJClaude and how incredibly wrong he is in regard to the "actions" of the Storj team and our pursuit of profit (of which I can thoroughly assure you is equal to exactly zero), I'm closing this issue and locking it as it does not belong in the issue tracking system for our API. 

Feel free to continue the finger pointing and free market rhetoric in the #payouts channel in community.storj.io, where you will learn from @pgerbes1 (our data scientist) that we are simply trying different models for payouts to understand the best way to foster a system that promotes better decentralization and works best for everyone.
