### ISSUE TITLE
Bucket resurrection 

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/bridge#342]
### Package Versions

Replace the values below using the output from `npm list storj-bridge`.

```
storj-bridge@4.3.2 /home/gordon/Code/storj-bridge
└── Storjcli: 4.0.0 | Core: 6.0.15
```

Replace the values below using the output from `node --version`.

```
v6.9.4
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
When i delete a bucket it is permanently deleted. 
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
If i delete a bucket and then try to add a bucket with the same name it brings back my old bucket that should have been deleted. 
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

```
C:\Users\Meije>storj add-bucket Libgen_torrent_repository

- [Sun Jan 29 2017 22:45:08 GMT+0000 (Greenwich Standard Time)] [info]   ID: 09ccf8a7bc94c885b2470f9d, Name: Libgen_torrent_repository, Storage: 0, Transfer: 0

- storj remove-bucket 09ccf8a7bc94c885b2470f9d

- storj add-bucket Libgen_torrent_repository
[Sun Jan 29 2017 23:00:24 GMT+0000 (Greenwich Standard Time)] [warn]   Request failed, reason: ESOCKETTIMEDOUT - retrying(true)...
[Sun Jan 29 2017 23:00:25 GMT+0000 (Greenwich Standard Time)] [info]   ID: 09ccf8a7bc94c885b2470f9d, Name: Libgen_torrent_repository, Storage: 0, Transfer: 0
```

**Comment by braydonf** [comment]
We tried to debug this issue by adding a callback to log the error, and inadvertently fixed the issue.

The bug was caused because `BucketEntry.remove({ bucket: req.params.id })` returns a promise and will not actually execute. It was fixed by adding a callback `BucketEntry.remove({ bucket: req.params.id }, (err) => { ... })`

Related:
- https://github.com/Storj/bridge/blob/fccb0c8dfba16b3049b0f2e841243bdb56112f20/lib/server/routes/buckets.js#L160-L161
- http://mongoosejs.com/docs/api.html#query_Query-remove

**Comment by MeijeSibbel** [comment]
Please reopen, this issue still persists.
