### ISSUE TITLE
Bridge is paying backdated for mirror shards

### ISSUE THREAD

**Issue by littleskunk** [storj/bridge#389]
### Package Versions

Replace the values below using the output from `npm list storj-bridge`.

```
└─┬ storjshare-daemon@2.5.1
  └── storj-lib@6.3.2
```

Replace the values below using the output from `node --version`.

```
v6.10.0
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

> This will create an additional mirror for all associated shards for a contact when the contact is unreachable for 1 hour in 24 hours.
> https://github.com/Storj/bridge/pull/374

The bridge should pay the farmer only for the time he stored the shard even if he gets a mirror hours or days later.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

I used a script to search for these mirrors. No result. All shards are stored for 90 days and the bridge will pay backdated for the shard. Worst case I receive the shard on the last day and will get the payment for all 90 days.

```
var storj = require('storj-lib');
var stream = require('readable-stream');

// insert your storage location here.
// on Windows you need double backslash. C:\\storjshare\\whatever
var persistence = new storj.EmbeddedStorageAdapter('/root/.storjshare/storjshare/shares/188071ba7cfd974a9e47b59e24b0737ebf845db3');
var manager = new storj.StorageManager(persistence);

var StorageAdapter = require('storj-lib/lib/storage/adapter');
var StorageItem = require('storj-lib/lib/storage/item');

var rstream = manager._storage.createReadStream();

rstream.on('data', function(item) {
  Object.keys(item.contracts).some(function(nodeID) {
    var contract = item.contracts[nodeID];
    if (contract.get('store_end') - contract.get('store_begin') < 7776000000) {
      console.info(JSON.stringify(item, null, 2));
    }
  });
});

rstream.on('end', function() {
  process.exit();
});
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Farm a few days and run the script.

**Comment by braydonf** [comment]
This should be closed with this https://github.com/Storj/bridge/issues/481

**Comment by littleskunk** [comment]
At the moment the farmer is able to verify the payout GBh calculation. If we fix this issue only on the bridge side the farmer can't verify the payout GBh calculation anymore. I would expect a fix on the farmer side as well or the farmer are not able to trust the payout calculation. They would have no way to verify it.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
