### ISSUE TITLE
Cannot list files in public pull buckets

### ISSUE THREAD

**Issue by prestwich** [storj/bridge#392]
### Expected Behavior

Buckets with the public `pull` permission set should return file metadata lists via `GET /buckets/{id}/files` to other users.

### Actual Behavior

When attempting to list files in a bucket with the public `pull` permission you get a not found error.

https://github.com/Storj/bridge/blob/master/lib/server/routes/buckets.js#L76-L101

### Steps to Reproduce

1. Create a public bucket.
2. Change users
3. Attempt to list files in the public bucket.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
