### ISSUE TITLE
Shard repair worker to recover lost shards

### ISSUE THREAD

**Issue by braydonf** [storj/bridge#395]
This will require that erasure encoding has been implemented on the client side, such that shards that go missing can be reconstructed by a bridge process that will repair the missing shard, and generate the necessary number of shard mirrors again. This process should be the last resort once a shard goes missing and all efforts have been made to keep a least 5 mirrors per shard.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
