### ISSUE TITLE
Multiuser and public sharing of buckets and bucket entries

### ISSUE THREAD

**Issue by braydonf** [storj/bridge#396]
Currently there are buckets which are associated with a single user and an encryption key. As this is the primary focus of an encrypted storage that only the user can access.

However, there are some use cases for buckets to be either associated with multiple users, an organization, as well as with the public.  Adding an *account* that defines a set of security properties can accommodate these different use cases. An *account* and can then be associated with buckets and bucket entries *instead* of a single user. The *account* would be similar to a *wallet* in cryptocurrency terms.

A user can then be a part of several *accounts*, and *accounts* can have several *users*. In the case of a shared account between two users, an encryption key can be derived via diffie-hellman between each user's *encryption key* *(and never shared with the bridge)*. Once this has been defined it can not be modified, as to meet the security expectations.

In the case of an *account* that is intended to be available for the general public, either no encryption key, or a predefined yet public available key (e.g. all null bytes or similar) can be used that is not associated with the user. Therefore these files that are uploaded are *clearly* intended to be made public.

**Comment by braydonf** [comment]
Spec draft: https://github.com/Storj/sips/pull/41

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
