### ISSUE TITLE
Additional authentication mechanisms

### ISSUE THREAD

**Issue by braydonf** [storj/bridge#397]
Provide several methods for authentication as a user based on popular standards.

A few ideas:
- OAuth - https://en.wikipedia.org/wiki/OAuth
- U2F - https://blog.trezor.io/secure-two-factor-authentication-with-trezor-u2f-e940fd5a60af#.nf341xqi7
- Two Factor - https://github.com/Storj/bridge/issues/154
- Associate PGP key (for emails)
- Support Yubikey (https://www.yubico.com/)
- Sign in via other services (Github, and etc.)

**Comment by dylanlott** [comment]
@bryanchriswhite and I are going to tackle 2FA once the GUI is done in Vue.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
