### ISSUE TITLE
Change bucket entry `file_id` to unique (non-deterministic)

### ISSUE THREAD

**Issue by braydonf** [storj/bridge#405]
There are several reason why we may want to have bucket entry ids always be unique, and can't be repeated. Currently the file_id is generated deterministically, which creates several issues:

1. Causes issues with keeping track of storage events when the same file_id is reused for different files, but with the same name and bucket
2. Restricts the ability to rename files by connecting the name to the file_id
3. Strangeness with using the same file_id when encrypting files

**Comment by braydonf** [comment]
We need to deprecate deterministic id, code is written, just need to flips the switch, and this will be closed.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
