### ISSUE TITLE
Fix issues with identical bucket entries creation, and duplicate storage events

### ISSUE THREAD

**Issue by braydonf** [storj/bridge#406]
Looks like there is an issue where it's possible to create the same bucket entry several times after each other. We've noticed this during testing, where the same file can be uploaded again and use the bucket entry.  

This is generating several storage events for the same activity, causing some issues with keeping track of total storage used. 

It also doesn't make much sense to create a bucket entry after it's already been created, and should be safe to call again without causing side effects (e.g. idempotent).

**Comment by braydonf** [comment]
We need to deprecate deterministic id, code is written, just need to flips the switch, and this will be closed.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
