### ISSUE TITLE
Nonces and timestamps

### ISSUE THREAD

**Issue by hwkns** [Storj/bridge#42]
The current documentation and the `metadisk-client` code both use a unix timestamp as the nonce:

```javascript
params.__nonce = Date.now();
```

This means the server only has to check if that nonce has been used in the last _n_ minutes, because it already knows that older timestamps are invalid, but this approach can be disastrous for multi-threaded clients, or even two different clients trying to make requests at the same time.  In short, a timestamp is not reliably unique enough to be used as a nonce.

Using a UUID instead of a timestamp would provide reliable uniqueness, but with this approach the server must store a massive amount of information (**all** the UUIDs **ever used** to make a request to the API) in order to validate nonces.

Using both a UUID and a timestamp would provide reliable uniqueness _and_ constraints on how much storage is required for validation:

> Let's say you decide to allow up to 15 minutes time difference between your clock and the client's and are keeping track of the nonce values in a database table. The unique key for the table is going to be a combination of 'client identifier', 'access token', 'nonce', and 'timestamp'. When a new request comes in, check that the timestamp is within 15 minutes of your clock then lookup that combination in your table. If found, reject the call, otherwise add that to your table and return the requested resource. Every time you add a new nonce to the table, delete any record for that 'client identifier' and 'access token' combination with timestamp older than 15 minutes.

http://stackoverflow.com/a/6876907/1784296

**Comment by niahmiah** [comment]
In the description above, I assume you are referring to UUID v4. 

- UUID v1 is based on timestamp + "MAC" address, so that could be used to easily check if it is > 15 minutes old, and would be more unique than just a timestamp. (MAC address is usually randomly generated as in https://github.com/broofa/node-uuid/blob/master/uuid.js#L115) 
- ObjectID is similar to UUID v1in that it is time based, sortable, queryable, etc, but with a different composition https://github.com/mongodb/js-bson/blob/master/lib/bson/objectid.js#L120

Using either of the above instead of a date would add uniqueness without making the nonce very large.

**Comment by niahmiah** [comment]
UUID v1 seems like a better choice considering that bridge-client has no mongo dependency. 

It looks like that we can do this without breaking things by changing the User model in "bridge" to make the nonce a String instead of a Number. Luckily, in Javascript, 3 == "3", so we can still support older clients sending a date (milliseconds/unix time) and keep the existing functionality, and also update the client to send UUID v1.

**Comment by gordonwritescode** [comment]
Sounds good to me, @niahmiah - hack away.

**Comment by gordonwritescode** [comment]
Be sure to update `doc/auth.md` too!

**Comment by gordonwritescode** [comment]
And I think the `apispec.json` swagger definition might need it too.

**Comment by hwkns** [comment]
Do what you want, but the UUID v1 spec is not reliably unique.  Some implementations might be, but others might not.

**Comment by niahmiah** [comment]
To address @hwkns comments above, I suggest an alternate way of handling this. See PR https://github.com/Storj/bridge/pull/70 for discussion. It does introduce a different behavior, so we should discuss before moving forward.

**Comment by gordonwritescode** [comment]
@niahmiah is this good to review and merge or still in progress?
