### ISSUE TITLE
Feature: Create a public API on the bridge for estimated payouts or for GB uploaded + GB/h accumulation for each node-ID.

### ISSUE THREAD

**Issue by MeijeSibbel** [storj/bridge#432]
## Idea one

 - The bridge already sums-up all the parameters that will determine a node's payout by default (GB/h + uploaded data) , take a snapshot of the network to get the mean values and finally combine this data with the payout formula to get the estimated SJCX payout amount for that point in time. Then make this data public via a API on the bridge. Parameters: nodeID , estimated payout.

## Idea two

- The bridge already sums-up all the parameters that will determine a node's payout (GB/h + uploaded data). Make this data public via a API on the Storj bridge so that farmers can look-up the values for their nodes.

## Idea three

- combine idea one and two, this will result in more parameters that will be given in the API for each node-ID.

**Comment by VanillaScent** [comment]
Please do make this! Would really appreciate it.
This would be handy for new users who want to see how much they make.

**Comment by JukeboxRhino** [comment]
I'm not sure how much the wantoo board gets seen (as in I really don't know) but I'll definitely vouch for this here. It would be a big improvement.

**Comment by KeirDavis1** [comment]
I think a combination of both is great. You could even apply some predictions (as an addon) for predictions. I think this'd be great.

**Comment by NateDevOfficial** [comment]
This would be awesome, and it gives motivation to keep going because they see how much they've made, without having to wait til the end of the month, and they might give up because they have to wait.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
