### ISSUE TITLE
Improve forgotten password handling

### ISSUE THREAD

**Issue by dylanlott** [storj/bridge#454]
# Expected behavior
User should input their email, and GUI should alert that if the email is found in our system, they'll have an email in their inbox with steps to reset their password. From there, the user should be linked over to a password reset flow, where they answer security questions or enter a pin or something. 

# Current Behavior
User enters their email and a new password. This is pretty vulnerable to social engineering attacks, as anyone can reset the password and hope that the user clicks the reset confirmation email. 

# Notes
Two factor authentication will help with this, but there is some work we can do here to make this more secure as well.

# Blockers
This should be done after 2FA and per-user password security is finished.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
