### ISSUE TITLE
Allow renter to set redundancy level

### ISSUE THREAD

**Issue by MeijeSibbel** [storj/bridge#476]
### Package Versions

Replace the values below using the output from `npm list storj-bridge`.

```
storj-bridge@0.6.5 /home/gordon/Code/storj-bridge
└── storj@0.6.5  -> /home/gordon/Code/storj-core
```

Replace the values below using the output from `node --version`.

```
v4.2.3
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
Allow the renter to set the redundancy levels (0- upper value)

- free tiers customers are not allowed to set redundancy
- Only paid tier users are allowed to set redundancy. 
- redundancy has to be set before uploading (prevents mirror creation attack)
- There is a upper limit to the number of mirrors that can be created.
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
Renters are currently not able to set a redundancy level.
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

**Comment by MeijeSibbel** [comment]
If we set the default redundancy level to 3-6, the price will be as advertised on the Storj website, if people want more mirrors they pay proportionally more. If they want only 1-2 mirrors, they will pay less that the advertised amount on the website.

**Comment by braydonf** [comment]
I think a better UX here would be to have "how long should this file be stored" as an option.

**Comment by kaloyan-raev** [comment]
I don't think that the redundancy is related only to "how long a file should be stored", if at all. It is implied that renters want to store files until deleting them.

Higher redundancy level reduces the risk of losing files and increases the distribution level across the world. The latter may be a use case on its own. Using the Storj network as CDN.

**Comment by braydonf** [comment]
Related https://github.com/Storj/billing/issues/71

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
