### ISSUE TITLE
Forgot password link issue

### ISSUE THREAD

**Issue by frlsazc** [storj/bridge#477]
### Package Versions

Replace the values below using the output from `npm list storj-bridge`.

i am a user of the bridge

Replace the values below using the output from `node --version`.

I used the internet site

### Expected Behavior

when i forgot my password to log into the storj internet site, I have an option to reset it. it's called "Forgot Password". I click on it and I received an email asking me to click on a link asking me to reset it.
Don't know what should happen after.

### Actual Behavior

When I click on on the "Forgot Password" link, I receive the mail. that's good.
In this mail, there is a link asking me to click on it to reset my password. I click on it. 
a new window opens in my browser, but the message is a JSON message: {"error":"User not found"}.

I add that my account exists as I was able to connect few seconds before this bug happens.
I was on safari and received the mail on gmail.

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. create an account and activate the account.
2. when connected to https://app.storj.io, logout and ask a password reset by clicking "Forgot Password link". Wait the mail comes
3. open the mail and click on the "reset password" link in it.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
