### ISSUE TITLE
Storj monitor w/ random shard audit

### ISSUE THREAD

**Issue by braydonf** [storj/bridge#480]
Currently the storj-monitor will send a PING to the farmer, this can be updated to perform an audit on a random shard.

**Comment by littleskunk** [comment]
If the ping fails the farmer will count as offline and the bridge will create a new mirror. As soon as he is back online he can go on farming without any lost contract.

If we change it to audit the farmer will lose one contract per Audit message. Does a farmer realy have to keep his farmer online nonstop? Not a single reboot is allowed? With a bad timing even a short `storjshare restart` can miss an audit.

**Comment by braydonf** [comment]
I think it takes currently around 6 failed pings to be considered offline (roughly), and that was calculated before we had reed solomon implemented, so that threshold could be increased and the number of mirrors (potentially). If there are repeat failures it's pretty much guaranteed that the farmer is offline.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
