### ISSUE TITLE
Add farmer storage events

### ISSUE THREAD

**Issue by braydonf** [storj/bridge#481]
As similar to the storage events that are used for billing, create a time based record of events that can be used for calculating farmer payouts in a way that can scale from monthly payments to instant payments with Ethereum state channels.

There are two new collections that will need to be added:

**Farmer Events**
```
{
  "nodeID": "e018b3892765c4a35aeb4f404d8fe5c21c5141b6",
  "payoutAddress"": "0xa7c221ae3137924e86bd7862fb9f05d5f362282f",
  "timestamp": 1502154813103,
  "downloadBandwidth": 100,
  "storage": 100
}
```
These events will be created when:
- A farmer receives data on upload (with a positive storage amount)
- A farmer goes offline, file is deleted, fails audit, or contract ends (with a negative storage value)
- A farmer delivers a file to a client (with a positive downloadBandwidth value)

As similar to debits generated from storage events, a collection will be updated periodically to calculate payouts. This collection will keep accounting for payouts, with positive values added from farmer events, and negative values when payouts are sent.

**Farmer Liability**
```
{
  "nodeID": "e018b3892765c4a35aeb4f404d8fe5c21c5141b6",
  "payoutAddress"": "0xa7c221ae3137924e86bd7862fb9f05d5f362282f",
  "timestamp": 1502154897441,
  "amount": 100
}
```

**Comment by pgerbes1** [comment]
It occurred to me waking up this morning that we might not want to expose the paymentAddress with nodeID. I know @littleskunk had some reservations about this on another PR.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
