### ISSUE TITLE
Setup bridge redundancy 

### ISSUE THREAD

**Issue by MeijeSibbel** [storj/bridge#483]
### Expected Behavior

The Storj bridge has multiple redundancies across the globe to prevent the Storj service from going down when the main bridge crashes, which happens allot currently.

### Actual Behavior

Currently there is only one Storj bridge, which is hosted in a Google data-center. If that google data-center goes offline, So will all the Storj Labs services, nobody will be able to upload, access the files...

Storj Should start looking at ways to increase bridge redundancy until federated bridges are implemented. Implying setting up fail-over bridges in different data-centers across the globe. This to prevent all the Storj services from going offline when the main bridge fails (which it currently does almost weekly).

**Comment by braydonf** [comment]
I edited the above description to be more readable (sans all the template).

**Comment by braydonf** [comment]
What's been discussed so far is to start moving some of the state of the bridge to the Ethereum block chain, in a way that that will not cause scaling issues. Identity and directories can be a start of this, however other tasks can be moved to be decentralized as well.

**Comment by braydonf** [comment]
FYI from the farmer side, config options to accept contracts and data from multiple bridges is in the works, see https://github.com/Storj/integration/pull/5/files Next we can streamline the process for new bridges to join with something such as https://github.com/Storj/sips/pull/20/files and then work on automating farmer payouts.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
