### ISSUE TITLE
Parity shards and storage events

### ISSUE THREAD

**Issue by braydonf** [storj/bridge#486]
Record storage event based on the stated original file size except if the total storage size is not more than 2/3 of the original size.

See: https://github.com/Storj/bridge/blob/master/lib/server/routes/buckets.js#L519

This check can be used to determine the size.
```
let dataSize = frame.size;
if ( frame.storageSize > (frame.size + frame.size * 2 / 3)) {
  dateSize = frame.storageSize;
}
```

2/3 used as that is what's used by default in https://github.com/Storj/libstorj/blob/master/src/uploader.c#L2428

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
