### ISSUE TITLE
Add ability to rename buckets and files

### ISSUE THREAD

**Issue by braydonf** [storj/bridge#488]
This currently depends on deprecating deterministic id, see notices in https://github.com/Storj/service-storage-models/blob/master/lib/models/bucketentry.js#L15-L18

Changing the bucket name or file name does not affect how the file is encrypted.

**Comment by kaloyan-raev** [comment]
I hope this is implemented in a way that changing file's or bucket's name does not change its ID. Keeping the ID the same would help clients to determine that a file or bucket has been renamed and not deleted.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
