### ISSUE TITLE
Change the way the free tier rate limit is structured at the bridge

### ISSUE THREAD

**Issue by MeijeSibbel** [storj/bridge#505]
### Package Versions

Replace the values below using the output from `npm list storj-bridge`.

```
storj-bridge@latest /home/gordon/Code/storj-bridge
└── storj@latest  -> /home/gordon/Code/storj-core
```

Replace the values below using the output from `node --version`.

```
latest
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
- New users that use Storj know how much they can upload and **are able** to upload this amount. 
- New users are made aware with normal and appropriate language (not some bridge limit error) that they cannot upload anymore.
- **remove the 3GB/h, 10GB/day limit, this is just a pain for everyone, set the limit at 25GB of storage, users can upload this amount right away without any bridge rate limit errors.

The current rate limit is just not working, it only gets in the way of things, which in this case yields angry customers that leave to use something else (e.g. SIA).
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
So right now from giving community support over the last year or so since the free tier was implemented we have received nothing but complaints from everyone that tries to upload to Storj. The reasons for this include:

1. Users know they get 25GB for free, but what they don't realize is that they can't upload more than 1.875GB per hour due to the 3GB/h limit and the fact that erasure encoding and uploading the parity shards makes the files bigger.
2. Users are not appropriately given feedback as to **why** they can't upload anymore, because to them, they still have 22GB of data that they can upload.
3. There is nowhere specified that there is a 3GB/h, 10GB/day and 25GB/month limit
4. Basically this rate limit which induces a file size limits prevents any free tier user from uploading their files that are bigger than 1-2GB.
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
