### ISSUE TITLE
Move payoutAddress to contact with from contract, address validation, and reduce contract storage size

### ISSUE THREAD

**Issue by braydonf** [storj/bridge#507]
This is related to SIP6 [contact updates](https://github.com/Storj/sips/blob/master/sip-0006.md#farmer-contact-discovery). The `payoutAddress` can be set per `contact` rather than on each shard `contract`. This will reduce the duplication of information on each `contract`, and payouts is currently using the last defined address. 

Contracts represent a bulk of the data currently in the database. Reducing the storage size will increase the scalability and costs for storing meta data cost. Furthermore there are other fields on a `contract` that are not needed and can be cleaned up.

There are also some inconsistencies with address and the hex encoding. Some address have mixed case encoding, others do not. This makes equality comparisons troublesome.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
