### ISSUE TITLE
Unable to send exchange report

### ISSUE THREAD

**Issue by littleskunk** [storj/bridge#512]
### Package Versions

Replace the values below using the output from `npm list storj-bridge`.

```
version | "7.0.1"
x-protocol-version | "1.2.0"
x-core-version | "8.0.0"
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
Farmer payout is based on exchange reports. The bridge has to accept them without errors.
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

In this case only unpaid mirror traffic but next time I could lose my downloadedByte payment.
```
{"level":"info","message":"Mirror download completed hash a8644ad9a3f2aa6fca768ad3d54794d7459f52bd size 101","timestamp":"2017-09-30T01:08:55.605Z"}
[...]
{"level":"warn","message":"Unable to send exchange report to bridge: https://api.storj.io, reason: socket hang up","timestamp":"2017-09-30T01:09:16.178Z"}
[...]
{"level":"info","message":"Mirror download completed hash a8644ad9a3f2aa6fca768ad3d54794d7459f52bd size 101","timestamp":"2017-09-30T01:09:28.211Z"}
[...]
{"level":"warn","message":"Unable to send exchange report to bridge: https://api.storj.io, reason: connect ETIMEDOUT 104.154.188.238:443","timestamp":"2017-09-30T01:11:35.593Z"}
```

**Comment by Jurisg** [comment]
Package Versions
daemon: 5.1.0, core: 8.1.0, protocol: 1.2.0

Actual Behavior

{"level":"info","message":"successfully mirrored shard hash 9f31a9a55ea7852f1f9e67867c98752f6e7ef088 size 101","timestamp":"2017-09-30T00:31:10.644Z"}
[...]
{"level":"warn","message":"Unable to send exchange report to bridge: https://api.storj.io, reason: socket hang up","timestamp":"2017-09-30T00:31:11.303Z"}

{"level":"info","message":"successfully mirrored shard hash 9d3335c34efef18d5a7b6a582aae37d058d7aa51 size 101","timestamp":"2017-09-30T00:54:32.864Z"}
[...]
{"level":"warn","message":"Unable to send exchange report to bridge: https://api.storj.io, reason: socket hang up","timestamp":"2017-09-30T00:54:54.985Z"}

{"level":"info","message":"successfully mirrored shard hash 9778537ee2846ce85bb89ebd0d497165a5c27ede size 101","timestamp":"2017-09-30T01:20:48.392Z"}
[...]
{"level":"warn","message":"Unable to send exchange report to bridge: https://api.storj.io, reason: read ECONNRESET","timestamp":"2017-09-30T01:20:53.271Z"}
{"level":"warn","message":"Unable to send exchange report to bridge: https://api.storj.io, reason: read ECONNRESET","timestamp":"2017-09-30T01:20:53.379Z"}
{"level":"warn","message":"Unable to send exchange report to bridge: https://api.storj.io, reason: socket hang up","timestamp":"2017-09-30T01:20:53.389Z"}

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
