### ISSUE TITLE
Bypassing PoW challenge

### ISSUE THREAD

**Issue by littleskunk** [storj/bridge#525]
### Package Versions

Replace the values below using the output from `npm list storj-bridge`.

```
"version":"7.2.2"
"x-protocol-version":"1.2.0"
"x-core-version":"8.3.1"
```

Replace the values below using the output from `node --version`.

```
v6.11.5
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

>A bridge will define a target difficulty to match an expected rate of total number of new contacts being added in a time period.
> - https://github.com/Storj/sips/blob/master/sip-0006.md#farmer-contact-discovery

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

Farmer can bypass PoW and add as many new contacts as he likes by sending PING, FIND_NODE or PUBLISH messages to the bridge renter worker.

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Disable `farmer._addBridgeContact` to make sure the farmer will never solve the PoW challenge.
2. Keep the farmer running for a few hours. He will send a lot of messages and some of them will hit the bridge renter worker. At some point the farmer is connected without solving the PoW challenge.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
