### ISSUE TITLE
Farmer with responseTime null will never receive any ALLOC message

### ISSUE THREAD

**Issue by littleskunk** [Storj/bridge#527]
### Package Versions

Replace the values below using the output from `npm list storj-bridge`.

```
"version":"7.2.2"
"x-protocol-version":"1.2.0"
"x-core-version":"8.3.1"
```

Replace the values below using the output from `node --version`.

```
v6.11.5
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
New farmer should receive a few ALLOC messages and reduce responseTime slowly.
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

We have a lot of new farmer with responseTime null. The bridge will never send them any ALLOC messages: https://github.com/Storj/bridge/blob/3134e47d0fd1ffed3591498c0af41a73faa2656d/lib/server/routes/frames.js#L172

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Create a new farmer without PoW registration. See https://github.com/Storj/bridge/issues/525 for more details.

**Comment by justsomedude4242** [comment]
this issue is happening again today. nobody can create any new nodes.

i just noticed on storjstat that before the 12/13 of october the lowest response time reported was 295, but after the 13th of october the lowest reported RT is always 0. so maybe look into what changed between the 11th and the 13th of october.

i suspectr there are currently hundreds of nodes with this problem and the users dont even know their nodes arent working (theres at least some otherwise storjstat wouldnt report lowest RT as 0)

many users will start farming run into this issue and even after months not get anything and leave angry

**Comment by braydonf** [comment]
Should be closed with https://github.com/Storj/bridge/pull/554
