### ISSUE TITLE
missing bucket pubkey validation

### ISSUE THREAD

**Issue by littleskunk** [Storj/bridge#53]
Unit test create an user with a public key:
https://github.com/littleskunk/bridge/blob/master/test/pubkey.integration.js#L18

Later I use the same key to create a bucket:
https://github.com/littleskunk/bridge/blob/master/test/pubkey.integration.js#L66

I would expect an error message because of duplicate pubkey.

**Comment by gordonwritescode** [comment]
This is actually expected. Adding a public key to a bucket does not register it or connect it to a user. Public keys added to a bucket are only capable of creating PUSH and PULL tokens for that specific bucket.

As such, the bridge does not care if you are adding a public key that is already registered, because it does not register it. Here is a use case:

* Bob creates a user account and *registers* a public key
* Alice, who is also a user, creates a bucket
* Alice wants to give Bob access to one of her buckets
* Bob wants to use his registered public key and gives it to Alice
* Alice adds the public key to her bucket so Bob can access it

If we don't allow registered public keys to be added to buckets, then Bob must generate a new keypair (which he *should* do anyway, but I don't think imposing that restriction affords us anything).

The key takeaway here: *public keys added to a bucket are not registered keys*.

**Comment by littleskunk** [comment]
Got it. Thank you for the good description. I will modify the open pull request.
