### ISSUE TITLE
SIP9 offline penalty doesn't create a new mirror

### ISSUE THREAD

**Issue by littleskunk** [storj/bridge#594]
### Package Versions

Replace the values below using the output from `npm list storj-bridge`.

```
{"title":"Storj Bridge",
"version":"8.0.0",
"description":"Access the Storj network using a simple REST API.",
"x-protocol-version":"1.2.0-STAGING",
"x-core-version":"8.7.2"}
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

My farmer log
```
{"level":"info","message":"Shard upload completed hash cd1268b718a47de86c34e2bff4170823fc0bdea6 size 16777216","timestamp":"2018-05-15T07:19:59.823Z"}
[...]
{"level":"info","message":"Mirror download completed hash cd1268b718a47de86c34e2bff4170823fc0bdea6 size 16777216","timestamp":"2018-05-15T07:20:41.329Z"}
{"level":"debug","message":"exchange report submitted: {\"dataHash\":\"cd1268b718a47de86c34e2bff4170823fc0bdea6\",\"token\":\"5a45a900812537b6ab8ca7fd96ae51a96515c4d1\",\"exchangeStart\":1526368806356,\"exchangeEnd\":1526368841329,\"exchangeResultCode\":1000,\"exchangeResultMessage\":\"SHARD_DOWNLOADED\"}","timestamp":"2018-05-15T07:20:42.406Z"}
```

Offline penalty was executed at `2018-05-15T08:35:55.343+0000`. I would expect a new mirror event.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

For this shard hash only one mirror event exists. The offline penalty doesn't create any new mirrors.
```
{ 
    "_id" : ObjectId("5afa8a241d193b21b19c743c"), 
    "token" : "5a45a900812537b6ab8ca7fd96ae51a96515c4d1", 
    "user" : null, 
    "client" : "bfed6ed8f8351ee64b55ed15c8901ba7a49b284b", 
    "farmer" : "1000051d66af778bebb916fffa2076c9ce944790", 
    "downloadBandwidth" : NumberInt(0), 
    "storage" : NumberInt(16777216), 
    "shardHash" : "cd1268b718a47de86c34e2bff4170823fc0bdea6", 
    "processed" : false, 
    "success" : false, 
    "timestamp" : ISODate("2018-05-15T07:20:04.833+0000"), 
    "__v" : NumberInt(0), 
    "clientReport" : {
        "exchangeStart" : ISODate("2018-05-15T07:20:06.356+0000"), 
        "exchangeEnd" : ISODate("2018-05-15T07:20:41.329+0000"), 
        "exchangeResultCode" : NumberInt(1000), 
        "exchangeResultMessage" : "SHARD_DOWNLOADED"
    }, 
    "farmerReport" : {
        "exchangeStart" : ISODate("2018-05-15T07:20:05.101+0000"), 
        "exchangeEnd" : ISODate("2018-05-15T07:20:46.428+0000"), 
        "exchangeResultCode" : NumberInt(1000), 
        "exchangeResultMessage" : "MIRROR_SUCCESS"
    }
}
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Start a SIP9 farmer and connect to the staging bridge.
2. Wait for a mirror download and go offline until the offline penalty gets triggered.
3. Query the storage event for this shard hash.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
