### ISSUE TITLE
SIP9 offline penalty executed only once

### ISSUE THREAD

**Issue by littleskunk** [storj/bridge#597]
### Package Versions

Replace the values below using the output from `npm list storj-bridge`.

```
{"title":"Storj Bridge",
"version":"8.0.0",
"description":"Access the Storj network using a simple REST API.",
"x-protocol-version":"1.2.0-STAGING",
"x-core-version":"8.7.2"}
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

Every time I go offline for too long I should lose all contracts.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

Offline penalty will be triggered only once.

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Start a SIP9 farmer and connect to the staging bridge.
2. Go offline for a few hours to trigger the offline penalty.
3. Go online for 2 hours per day to get new shards.
4. Offline penalty will not be triggered a second time. Bad farmer can keep his contracts.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
